version: '3'

services:
  nginx-rtmp:
    image: bahorn/nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
  redis:
    image: redis
    ports:
      - 6379:6379
